/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "juyraadfloncqgqgmgve"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eXJhYWRmbG9uY3FncWdtZ3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjcxMTEsImV4cCI6MjA3MTk0MzExMX0.pqdVEHIHDeq8FTHV44GpHv8F-_wb-UH8ZO4n2qtVpVE"